# Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Це ДЗ передбачене під виконання на локальній машині. Виконання з Google Colab буде суттєво ускладнене.

## Підготовка
1. Переконайтесь, що у вас встановлены необхідні бібліотеки:
   ```bash
   pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv
   ```

2. Створіть файл `.env` з параметрами підключення до бази даних classicmodels. Базу даних ви можете отримати через

  - docker-контейнер згідно існтрукції в [документі](https://www.notion.so/hannapylieva/Docker-1eb94835849480c9b2e7f5dc22ee4df9), також відео інструкції присутні на платформі - уроки "MySQL бази, клієнт для роботи з БД, Docker і ChatGPT для запитів" та "Як встановити Docker для роботи з базами даних без терміналу"
  - або встановивши локально цю БД - для цього перегляньте урок "Опціонально. Встановлення MySQL та  БД Сlassicmodels локально".
  
  Приклад `.env` файлу ми створювали в лекції. Ось його обовʼязкове наповнення:
    ```
    DB_HOST=your_host
    DB_PORT=3306 або 3307 - той, який Ви налаштували
    DB_USER=your_username
    DB_PASSWORD=your_password
    DB_NAME=classicmodels
    ```
  Якщо ви створили цей файл під час перегляду лекції - **новий створювати не треба**. Замініть лише назву БД, або пропишіть назву в коді створення підключення (замість отримання назви цільової БД зі змінних оточення). Але переконайтесь, що до `.env` файл лежить в тій самій папці, що і цей ноутбук.

  **УВАГА!** НЕ копіюйте скрит для **створення** `.env` файлу. В лекції він наводиться для прикладу. І давалось пояснення, що в реальних проєктах ми НІКОЛИ не пишемо доступи до бази в коді. Копіювання скрипта для створення `.env` файлу сюди в ДЗ буде вважатись грубою помилкою і ми зніматимемо бали.

3. Налаштуйте підключення через SQLAlchemy до БД за прикладом в лекції.

Рекомендую вивести (відобразити) змінну engine після створення. Вона має бути не None! Якщо None - значить у Вас не підтягнулись налаштування з .env файла.

Ви також можете налаштувати параметри підключення до БД без .env файла, просто прописавши текстом в відповідних місцях. Це - не рекомендований підхід.


## Завдання

### Завдання 1: Оновлення інформації про клієнта (2 бали)

**Створіть функцію для оновлення контактної інформації клієнта за його номером** з наступними можливостями:
- Оновлення телефону клієнта
- Оновлення email (якщо поле існує в таблиці)

Опціонально, якщо вам хочеться більше практики:
- Логування змін в окрему таблицю

Використайте підхід з параметризованими запитами через `text()` та `UPDATE` оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом
```
  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
```

Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [9]:
import datetime
import requests
import json
import os

from dotenv import load_dotenv
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine, text, MetaData, Table
from sqlalchemy.orm import sessionmaker

In [12]:
def create_connection():
    """
    Створює підключення через SQLAlchemy
    """
    # Завантажуємо змінні середовища
    #load_dotenv()
    load_dotenv(dotenv_path=r'C:\Users\mazur\data_analysis\notebooks\.env.txt')

    # Отримуємо параметри з environment variables
    host = os.getenv('DB_HOST', 'localhost')
    port = os.getenv('DB_PORT', '3306')
    user = os.getenv('DB_USER')
    password = os.getenv('DB_PASSWORD')
    database = os.getenv('DB_NAME')

    if not all([user, password, database]):
        raise ValueError("Не всі параметри БД задані в .env файлі!")

    # Створюємо connection string
    connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"

    # Створюємо engine з connection pooling
    engine = create_engine(
        connection_string,
        pool_size=2,           # Розмір пулу підключень
        max_overflow=20,        # Максимальна кількість додаткових підключень
        pool_pre_ping=True,     # Перевірка підключення перед використанням
        echo=False              # Логування SQL запитів (True для debug)
    )

    # Тестуємо підключення
    try:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT 1"))
            result.fetchone()

        print("✅ Підключення до БД успішне!")
        print(f"🔗 {user}@{host}:{port}/{database}")
        print(f"⚡ Engine: {engine}")

        return engine

    except Exception as e:
        print(f"❌ Помилка підключення: {e}")
        return None

# Створюємо підключення
engine = create_connection()

✅ Підключення до БД успішне!
🔗 root@127.0.0.1:3306/classicmodels
⚡ Engine: Engine(mysql+pymysql://root:***@127.0.0.1:3306/classicmodels)

In [ ]:
def update_customer_info_transaction(engine, cust_no, new_phone):
       
    # чи існує співробітник 
    check_query = text("""
        select customerNumber, contactFirstName, contactLastName , phone
        from classicmodels.customers
        where customerNumber = :cust_no
    """)

    with engine.connect() as conn:
        result = conn.execute(check_query, {'cust_no': cust_no})
        customer = result.fetchone()

        if not customer:
            print(f"❌ Клієнт {cust_no} не знайдений")
            return False
     
    name = f"{customer[1]} {customer[2]}"
    print(f"👤 Міняємо номер телефона клієнта  {name} (ID: {cust_no})")

     #  створюємо нове підключення для транзакції
    with engine.connect() as conn:
        with conn.begin():
            try:
                update_phone_query = text("""
                    UPDATE classicmodels.customers
                    SET phone = :new_phone
                    WHERE customerNumber = :cust_no
                """)

                result1 = conn.execute(
                    update_phone_query, 
                    {'new_phone': new_phone, 'cust_no': cust_no}
                )
                print(f"✅ Крок 1: ЗЗмінено поточний телефон (оновлено {result1.rowcount} записів)")
             
            except Exception as e:
                print(f"❌ Помилка при зміні телефону: {e}")
                print("🔄 Всі зміни автоматично скасовано (ROLLBACK)")
                return False
            
            # Тестуємо підвищення співробітника
cust_no = 114
success = update_customer_info_transaction(
    engine,
    cust_no,
    new_phone ='13 9520 4555'
)

👤 Міняємо номер телефона клієнта  Peter Ferguson (ID: 114)
✅ Крок 1: ЗЗмінено поточний телефон (оновлено 1 записів)

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [44]:
def create_new_order_transaction(engine, p_code, cust_no, quantity, status, price_each, order_line):
    from datetime import date
    today = date.today()

     #  створюємо нове підключення для транзакції
    with engine.connect() as conn:
        with conn.begin():
            try:
                # Крок 1: Додаємо нове замовлення
                new_order_id = conn.execute(text("""
                    SELECT IFNULL(MAX(orderNumber), 0) + 1
                    FROM classicmodels.orders
                """)).scalar()

                add_new_order_query = text("""
                    INSERT INTO classicmodels.orders (orderNumber, orderDate, requiredDate, status, customerNumber)
                    VALUES (:order_no, :today, :today, :status, :cust_no)
                """)

                result1 = conn.execute(
                    add_new_order_query, 
                    {'order_no':new_order_id, 'today': today, 'requiredDate': today, 'status': status, 'cust_no': cust_no}
                )
                print(f"Нове замовлення: {new_order_id}")

                print(f"✅ Крок 1: Додано нове замовлення (оновлено {result1.rowcount} записів)")

                # Крок 2: Додаємо деталі замовлення в orderdetails
                add_new_order_details_query = text("""
                    INSERT INTO classicmodels.orderdetails (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
                    VALUES (:new_order_id, :p_code, :quantity, :price_each, :order_line)
                """)

                result2 = conn.execute(
                    add_new_order_details_query, 
                    {'new_order_id': new_order_id, 'p_code': p_code, 'quantity': quantity, 'price_each': price_each, 'order_line': order_line}
                )
                print(f"✅ Крок 2: Додані деталі замовлення (оновлено {result2.rowcount} записів)")

                # Крок 3: Перевіряємо чи є на складі
                check_instock_query = text("select productCode, quantityInStock from classicmodels.products where productCode = :p_code")

                result = conn.execute(check_instock_query, {'p_code': p_code})
                product_instock = result.fetchone()

                if product_instock.quantityInStock < quantity:
                    print(f"❌ Недостатньо товару на складі. Доступно: {product_instock.quantityInStock}")
                    return False
            
                # Крок 4: Заменшуємо кількість товарів на складі
                decrease_quantity_query = text("""
                    UPDATE classicmodels.products
                    SET quantityInStock = (quantityInStock - :quantity)
                    WHERE productCode = :p_code
                """)

                result4 = conn.execute(decrease_quantity_query, {'quantity': quantity, 'p_code': p_code})
                print(f"✅ Крок 4: Зменшено кількість товарів на складі (оновлено {result4.rowcount} записів)")

                return new_order_id
        
            except Exception as e:
                print(f"❌ Помилка при оформленні замовлення: {e}")
                print("🔄 Всі зміни автоматично скасовано (ROLLBACK)")
                return False
            
            # Тестуємо оформлення замовлення
p_code = 'S12_1108'
cust_no = 363
quantity = 1
status = 'abc'
price_each = 2
order_line = 3

new_order_id = create_new_order_transaction(
    engine,
    p_code,
    cust_no,
    quantity,
    status,
    price_each,
    order_line
)

Нове замовлення: 10435
✅ Крок 1: Додано нове замовлення (оновлено 1 записів)
✅ Крок 2: Додані деталі замовлення (оновлено 1 записів)
✅ Крок 4: Зменшено кількість товарів на складі (оновлено 1 записів)

In [ ]:
# Дивимось поточну інформацію по створеному замовленню Orders
check_result_query = text("""
    SELECT * 
    FROM classicmodels.orders
    WHERE orderNumber = :order_no
""")

df_result = pd.read_sql(
    check_result_query,
    engine,
    params={'order_no': new_order_id}
)

print("Нове замовлення додано в табл Orders:")
display(df_result)

Нове замовлення додано в табл Orders:

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10435,2026-03-14,2026-03-14,None,abc,None,363

In [47]:
# Дивимось поточну інформацію по створеному замовленню OrderDetails
check_order_details_query = text("""
    select * from classicmodels.orderdetails
    where orderNumber = :order_no
""")

df_result_details = pd.read_sql(
    check_order_details_query,
    engine,
    params={'order_no': new_order_id}
)

print("Деталі замовлення додано в табл OrderDetails:")
display(df_result_details)

Деталі замовлення додано в табл OrderDetails:

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10435    S12_1108                1        2.0                3

In [48]:
# Дивимось поточну інформацію по залишках товару
check_quantityInStock_query = text("""
    select productCode, quantityInStock from classicmodels.products
    where productCode = :p_code
""")

df_result_quantityInStock = pd.read_sql(
    check_quantityInStock_query,
    engine,
    params={'p_code': p_code}
)

print("Кількість на складі:")
display(df_result_quantityInStock)

Кількість на складі:

  productCode  quantityInStock
0    S12_1108             3615